### ISSUE TITLE
progress and real number of collected items

### ISSUE THREAD

**Issue by Floghi** [ssrikanta/pytest-progress#1]
Hello,
i noticed that the value you used to show the actual progress of run, **len(items)**,

```
def pytest_collection_modifyitems(session, config, items):
    terminal_reporter = config.pluginmanager.getplugin('terminalreporter')
    if terminal_reporter:
        terminal_reporter.tests_count = len(items)
```

is in fact the total number of collected items, but is different from the real number of tests that will be launched as we can deselect with options like -k, -m,.. 
thus the only real number of tests must be something like,

```
def pytest_collection_finish(session):
    terminal_reporter = session.config.pluginmanager.getplugin('terminalreporter')
    if terminal_reporter:
        terminal_reporter.tests_count = len(session.items)
```

where **session.items** is _items collected - items deselected._

The result is we go from:

> 
> collected 184 items
> Collected after deselection 1 items
> 
> pytest\sdk\functions\test_babtts_write.py::test_BabTTS_Write_FILE_NULL_TEXTFILE[0-alice22k_hq-32] PASSED
> ____ 1 of 184 completed, 1 Pass, 0 Fail, 0 Skip, 0 XPass, 0 XFail, 0 Error ____
> 
> ====== 183 tests deselected by '-ktest_BabTTS_Write_FILE_NULL_TEXTFILE' =======
> ================== 1 passed, 183 deselected in 2.71 seconds ===================

to

> 
> collected 184 items
> Collected after deselection 1 items
> 
> pytest\sdk\functions\test_babtts_write.py::test_BabTTS_Write_FILE_NULL_TEXTFILE[0-alice22k_hq-32] PASSED
> _____ 1 of 1 completed, 1 Pass, 0 Fail, 0 Skip, 0 XPass, 0 XFail, 0 Error _____
> 
> ====== 183 tests deselected by '-ktest_BabTTS_Write_FILE_NULL_TEXTFILE' =======
> ================== 1 passed, 183 deselected in 2.73 seconds ===================

Is it envisageable that this _fix_ is available in a future version ?

**Comment by ssrikanta** [comment]
@Floghi Thank you very much for the detailing.
Changes are on the way,

**Comment by ssrikanta** [comment]
#3 Fixes the issue
