### ISSUE TITLE
skipped test are not counted when pytest-rerunfailures is enabled

### ISSUE THREAD

**Issue by henzef** [ssrikanta/pytest-progress#11]
When running basicly any testsuite with skipped test, the skipped tests are not counted. minimal example:

    import pytest
    @pytest.mark.skip()
    def test_skipalot():
        pass

when running the above with `pytest --reruns=0 --show-progress` the status line is correct:
`_ 1 of 1 completed, 0 Pass, 0 Fail, 1 Skip, 0 XPass, 0 XFail, 0 Error, 0 ReRun _`
when running the above with `pytest --reruns=1 --show-progress` the status line is wrong:
`_ 0 of 1 completed, 0 Pass, 0 Fail, 0 Skip, 0 XPass, 0 XFail, 0 Error, 0 ReRun _`

**Comment by ssrikanta** [comment]
#12 Should fix this issue.
