### ISSUE TITLE
Can examples be added to the docs?

### ISSUE THREAD

**Issue by InbarRose** [ssrikanta/pytest-progress#17]
It would be great to see a sample output of some tests with all variations of --show-progress/--verbose

**Comment by ssrikanta** [comment]
@InbarRose  will update docs soon

**Comment by ssrikanta** [comment]
In progress, will be added soon
Though there is delay in looking into it 🙂

**Comment by ssrikanta** [comment]
Commands have been added, detailed output can be seen running the given tests.
