### ISSUE TITLE
incorrect progress is seen when used with pytest json report plugin

### ISSUE THREAD

**Issue by rakesh556575** [ssrikanta/pytest-progress#18]
tests.py::test1 PASSED
_ 2 of 2 completed, 2 Pass, 0 Fail, 0 Skip, 0 XPass, 0 XFail, 0 Error, 0 ReRun _
_ 2 of 2 completed, 2 Pass, 0 Fail, 0 Skip, 0 XPass, 0 XFail, 0 Error, 0 ReRun _

tests.py::test2 PASSED
_ 4 of 2 completed, 4 Pass, 0 Fail, 0 Skip, 0 XPass, 0 XFail, 0 Error, 0 ReRun _
_ 4 of 2 completed, 4 Pass, 0 Fail, 0 Skip, 0 XPass, 0 XFail, 0 Error, 0 ReRun _

**Comment by ssrikanta** [comment]
@rakesh556575  could you please attach your sample test script

**Comment by rakesh556575** [comment]
def test1():
    assert 1==1

def test2():
    assert 2==2

plugins version:
pytest-progress==1.2.2
pytest-json-report==1.4.1
pytest==6.2.5


additional arguments:
--show-progress  --junitxml=JUnit_Report.xml --json-report

**Comment by ssrikanta** [comment]
New version fixes this issue
