### ISSUE TITLE
Reported progress is always 0 with pytest-rerunfailures plugin (regression >=1.2.3)

### ISSUE THREAD

**Issue by henzef** [ssrikanta/pytest-progress#25]
Hi,
pytest-progress-1.2.2 is the last version that works for me in combination with the pytest-rerunfailures plugin

Given the following example file:

    def test_a(): pass
    def test_b(): pass

I get the following output with 1.2.2:

    $ pytest --show-progress test_foo.py --reruns=2 | cat
    ============================= test session starts ==============================
    platform linux -- Python 3.9.2, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
    rootdir: /home/pi
    plugins: rerunfailures-10.2, reportlog-0.1.2, progress-1.2.2
    collected 2 items

    test_foo.py .
    _ 1 of 2 completed, 1 Pass, 0 Fail, 0 Skip, 0 XPass, 0 XFail, 0 Error, 0 ReRun _

    test_foo.py .
    _ 2 of 2 completed, 2 Pass, 0 Fail, 0 Skip, 0 XPass, 0 XFail, 0 Error, 0 ReRun _
                                                                             [100%]
    ============================== 2 passed in 0.03s ===============================

pytest-progress 1.2.3 fails and 1.2.4 yields:

    $ pytest --show-progress test_foo.py --reruns=2 | cat
    ============================= test session starts ==============================
    platform linux -- Python 3.9.2, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
    rootdir: /home/pi
    plugins: rerunfailures-10.2, reportlog-0.1.2, progress-1.2.4
    collected 2 items

    test_foo.py .
    _ 0 of 2 completed, 0 Pass, 0 Fail, 0 Skip, 0 XPass, 0 XFail, 0 Error, 0 ReRun _

    test_foo.py .
    _ 0 of 2 completed, 0 Pass, 0 Fail, 0 Skip, 0 XPass, 0 XFail, 0 Error, 0 ReRun _
                                                                             [100%]
    ============================== 2 passed in 0.03s ===============================

**Comment by ssrikanta** [comment]
closed with #26
