### ISSUE TITLE
Counts mismatch

### ISSUE THREAD

**Issue by abhilashcae** [ssrikanta/pytest-progress#4]
## Description
I have four tests where in one of them fails. The count in the progress shown has a mismatch. Attached are the logs of the mismatch.

Note: This is a really useful plugin to track the progress. Thanks for this.
[pytest progress logs.txt](https://github.com/ssrikanta/pytest-progress/files/832723/pytest.progress.logs.txt)

@ssrikanta

**Comment by ssrikanta** [comment]
Can you please post sample test file

**Comment by abhilashcae** [comment]
@ssrikanta - Here you go. They have nothing but some log statements and an assert 0 in one test to purposefully fail it. In my pytest.ini file I have set --rerun 1 so that the failed test runs once more.


[test_one_sample.txt](https://github.com/ssrikanta/pytest-progress/files/845652/test_one_sample.txt)
[test_three_one_more.txt](https://github.com/ssrikanta/pytest-progress/files/845650/test_three_one_more.txt)
[test_two_another.txt](https://github.com/ssrikanta/pytest-progress/files/845651/test_two_another.txt)

**Comment by ssrikanta** [comment]
@abhilashcae So this happens only when  you set `--rerun 1` in  your ini file??

**Comment by abhilashcae** [comment]
No @ssrikanta , this happens irrespective of `--rerun 1`

**Comment by ssrikanta** [comment]
From your log file i could see there is no status for few of the tests, so what exactly happening there??
Below is extract from your log file, you could observe that first test doesn't show any status.
but the PASS count of our progress plugin has increased.

```
collected 4 items 

test_one_sample.py::TestOneSample::test_one_sample 
___________________________________________________________________ 1 of 4 completed, 1 Pass, 0 Fail, 0 Skip, 0 XPass, 0 XFail, 0 Error ____________________________________________________________________

test_one_sample.py::TestOneSample::test_one_sample PASSED
___________________________________________________________________ 2 of 4 completed, 2 Pass, 0 Fail, 0 Skip, 0 XPass, 0 XFail, 0 Error ____________________________________________________________________

test_one_sample.py::TestOneSample::test_inside_one 
___________________________________________________________________ 3 of 4 completed, 3 Pass, 0 Fail, 0 Skip, 0 XPass, 0 XFail, 0 Error ____________________________________________________________________

test_one_sample.py::TestOneSample::test_inside_one PASSED
___________________________________________________________________ 4 of 4 completed, 4 Pass, 0 Fail, 0 Skip, 0 XPass, 0 XFail, 0 Error ____________________________________________________________________

test_three_one_more.py::TestThreeOneMore::test_three_one_more 
___________________________________________________________________ 5 of 4 completed, 5 Pass, 0 Fail, 0 Skip, 0 XPass, 0 XFail, 0 Error ____________________________________________________________________

test_three_one_more.py::TestThreeOneMore::test_three_one_more PASSED
___________________________________________________________________ 6 of 4 completed, 6 Pass, 0 Fail, 0 Skip, 0 XPass, 0 XFail, 0 Error ____________________________________________________________________

test_two_another.py::TestTwoAnother::test_two_another 
___________________________________________________________________ 7 of 4 completed, 6 Pass, 1 Fail, 0 Skip, 0 XPass, 0 XFail, 0 Error ____________________________________________________________________

test_two_another.py::TestTwoAnother::test_two_another RERUN
test_two_another.py::TestTwoAnother::test_two_another 
___________________________________________________________________ 8 of 4 completed, 6 Pass, 2 Fail, 0 Skip, 0 XPass, 0 XFail, 0 Error ____________________________________________________________________

test_two_another.py::TestTwoAnother::test_two_another FAILED
_____________________________________________________________________________________ TestTwoAnother.test_two_another ______________________________________________________________________________________

self = <tests.test_two_another.TestTwoAnother instance at 0x11002df38>, driver = <appium.webdriver.webdriver.WebDriver (session="08735045-85cf-44c4-9055-13ced670f1a6")>

    def test_two_another(self, driver):
        self.logger.info('STARTING TEST : ' + inspect.stack()[0][3])
        self.logger.info('IN THE MID OF TEST : ' + inspect.stack()[0][3])
        self.logger.info('COMPLETED TEST : ' + inspect.stack()[0][3])
        self.logger.info('AFTER THE TEST : ' + inspect.stack()[0][3])
>       assert 0
E       assert 0

test_two_another.py:13: AssertionError
___________________________________________________________________ 9 of 4 completed, 6 Pass, 3 Fail, 0 Skip, 0 XPass, 0 XFail, 0 Error ____________________________________________________________________

===Flaky Test Report===


===End Flaky Test Report===
===================================================================== 1 failed, 3 passed, 2 pytest-warnings, 1 rerun in 38.50 seconds ======================================================================

```

**Comment by ssrikanta** [comment]
i don't see the issue with your py.tests as well

**Comment by abhilashcae** [comment]
>From your log file i could see there is no status for few of the tests, so what exactly happening there??

I see them only after using the plugin (test name gets printed twice. Once before running and once after). Without plugin it prints just once.

**Comment by ssrikanta** [comment]
Please share your python and pytest erosion as well, BTW printing tests name twice is not by our plugin, becoz we print only test count we don't have print statements for test name.
Please share list of pytest plugins installed as well. 
Since I am not able to reproduce issue from my end it's been difficult.  To give a fix

**Comment by abhilashcae** [comment]
@ssrikanta - I was running the tests from `tests` package itself. When I ran the tests from project root directory it works fine. Great plugin! Thanks! Maybe running from tests package could be considered as an enhancement?
